title: Vladislav Kurenkov
url: "https://vkurenkov.me"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-47632294-6

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Template by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Github"
   link: "https://github.com/vkurenkov"
 - name: "All Paper Submissions"
   link: "https://docs.google.com/spreadsheets/d/1nfNlxieYYpb6yEen2TTqWL_SEz9tmoWTY8KHUtzmN4M/edit#gid=0"
